class CurrencyValidator {
  static readonly currencyCodes = [
    'BOB',
    'BOV',
    'GHS',
    'XAF',
    'GYD',
    'GMD',
    'GBP',
    'EUR',
    'GTQ',
    'USD',
    'XDR',
    'XCD',
    'DKK',
    'GNF',
    'XOF',
    'NAD',
    'ZAR',
    'AUD',
    'NGN',
    'SSP',
    'NPR',
    'NOK',
    'XPF',
    'NZD',
    'NIO',
    'DOP',
    'LAK',
    'LRD',
    'RUB',
    'LBP',
    'LSL',
    'RON',
    'RWF',
    'LYD',
    'CHF',
    'MGA',
    'MOP',
    'MKD',
    'MWK',
    'MYR',
    'MXN',
    'MXV',
    'MAD',
    'MUR',
    'MRU',
    'MZN',
    'MDL',
    'MVR',
    'MNT',
    'MMK',
    'VUV',
    'BHD',
    'BBD',
    'BSD',
    'BDT',
    'BMD',
    'VEF',
    'VND',
    'BYR',
    'BZD',
    'BAM',
    'BWP',
    'BIF',
    'BTN',
    'INR',
    'BGN',
    'BRL',
    'BND',
    'WST',
    'SAR',
    'STN',
    'RSD',
    'SCR',
    'SHP',
    'SOS',
    'SBD',
    'SDG',
    'SRD',
    'LKR',
    'SZL',
    'SEK',
    'CHE',
    'CHW',
    'SYP',
    'XSU',
    'SLL',
    'ANG',
    'SGD',
    'AED',
    'AWG',
    'AMD',
    'ARS',
    'USN',
    'ISK',
    'HTG',
    'AZN',
    'AFN',
    'XUA',
    'ALL',
    'DZD',
    'AOA',
    'ERN',
    'ETB',
    'SVC',
    'YER',
    'OMR',
    'HNL',
    'JOD',
    'UGX',
    'UYI',
    'UYU',
    'UZS',
    'UAH',
    'IQD',
    'IRR',
    'ILS',
    'EGP',
    'IDR',
    'JPY',
    'JMD',
    'ZMW',
    'GEL',
    'CNY',
    'DJF',
    'GIP',
    'ZWL',
    'CZK',
    'CLF',
    'CLP',
    'CVE',
    'KZT',
    'QAR',
    'KHR',
    'CAD',
    'KES',
    'KYD',
    'KMF',
    'CRC',
    'COP',
    'COU',
    'CDF',
    'CUC',
    'CUP',
    'KWD',
    'HRK',
    'KGS',
    'TWD',
    'TJS',
    'TZS',
    'THB',
    'TRY',
    'TOP',
    'TMT',
    'TND',
    'TTD',
    'PAB',
    'PYG',
    'PKR',
    'PGK',
    'PEN',
    'FKP',
    'PLN',
    'FJD',
    'PHP',
    'KRW',
    'KPW',
    'HUF',
    'HKD',
  ];
  static validateCurrencyCode(currencyCode: string): void {
    if (!CurrencyValidator.currencyCodes.includes(currencyCode)) {
      throw new Error(`Invalid currency code: ${currencyCode}`);
    }
  }

  static validateLocaleCode(localeCode: string): void {
    const supported = Intl.NumberFormat.supportedLocalesOf([localeCode]);
    if (!supported || supported.length === 0) {
      throw new Error(`Invalid locale code: ${localeCode}`);
    }
  }
}

export class CurrencyInfo {
  private readonly numberFormat: Intl.NumberFormat;

  constructor(
    private readonly currencyCode: string,
    private readonly localeCode: string,
    private readonly minimumFractionDigits: number = 2,
    private readonly maximumFractionDigits: number = 2,
  ) {
    CurrencyValidator.validateCurrencyCode(currencyCode);
    CurrencyValidator.validateLocaleCode(localeCode);

    this.numberFormat = new Intl.NumberFormat(localeCode, {
      style: 'currency',
      currency: currencyCode,
      minimumFractionDigits: this.minimumFractionDigits,
      maximumFractionDigits: this.maximumFractionDigits,
    });
  }

  getCurrencyCode(): string {
    return this.currencyCode;
  }

  getLocaleCode(): string {
    return this.localeCode;
  }

  format(amount: number): string {
    return this.numberFormat.format(amount);
  }
}
